# ###---Wallpaper---###

wallpaper {
    monitor = DP-3
    path = /home/andrew/Pictures/Wallpapers/abstract_blue_wave.png
    fit_mode = cover
}

# Optional but recommended: a fallback for any other monitor
wallpaper {
    monitor =
    path = /home/andrew/Pictures/Wallpapers/abstract_blue_wave.png
    fit_mode = cover
}

ipc = on
splash = false

