# ###---Wallpaper---###

wallpaper {
    monitor = DP-2
    path = /home/andrew/Pictures/Wallpapers/3840x2160/symmetry-geometric-colorful-lines-3840x2160-7716.jpg
    fit_mode = cover
}

# Optional but recommended: a fallback for any other monitor
wallpaper {
    monitor =
    path = /home/andrew/Pictures/Wallpapers/3840x2160/symmetry-geometric-colorful-lines-5k-3840x2160-7762.jpg
    fit_mode = cover
}

ipc = on
splash = false

