###---Wallpaper---###
# Path to wallpaper
preload = /home/andrew/Pictures/Wallpapers/oneplus-6t-stock-abstract-1920x1080_55964-mm-90.jpg
preload = /home/andrew/Pictures/Wallpapers/oneplus-6t-stock-abstract-1920x1080_55964-mm-90_flip.jpg
# Set wallpaper for Monitor 1
wallpaper = DP-1,/home/andrew/Pictures/Wallpapers/oneplus-6t-stock-abstract-1920x1080_55964-mm-90.jpg
# Set wallpaper for Monitor 2
wallpaper = HDMI-A-2,/home/andrew/Pictures/Wallpapers/oneplus-6t-stock-abstract-1920x1080_55964-mm-90_flip.jpg

splash = false
